schema_version: 1

context:
  version: 1.6.1
  mpi_prefix: "mpi_${{ mpi }}"

recipe:
  name: spla
  version: ${{ version }}

source:
  - url: https://github.com/eth-cscs/spla/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 62b51e6ce05c41cfc1c6f6600410f9549a209c50f0331e1db41047f94493e02f

build:
  number: 4
  string: mpi_${{ mpi }}_h${{ hash }}_${{ build_number }}
  skip:
    - win

outputs:
  - package:
      name: spla
    build:
      script: build-spla.sh
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("fortran") }}
        - ${{ mpi }}
        - cmake >=3.18
        - ninja
        - pkg-config
      host:
        - ${{ mpi }}
        - _openmp_mutex
        - libcblas
        - "openblas * *openmp_*"
      run:
        - ${{ mpi }}
        - _openmp_mutex
        - libcblas
        - "openblas * *openmp_*"
    tests:
      - package_contents:
          lib:
            - libspla
    about:
      summary: Specialized Linear Algebra (SpLA) shared library, tailored for computational material science codes.
  - package:
      name: spla-static
    build:
      script: build-spla.sh
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("fortran") }}
        - ${{ mpi }}
        - cmake >=3.18
        - ninja
        - pkg-config
      host:
        - ${{ mpi }}
        - _openmp_mutex
        - libcblas
        - "openblas >=0.3.30 *openmp_*"
      run:
        - ${{ mpi }}
        - _openmp_mutex
        - libcblas
        - "openblas >=0.3.30 *openmp_*"
    tests:
      - package_contents:
          lib:
            - libspla.a
    about:
      summary: Specialized Linear Algebra (SpLA) static library, tailored for computational material science codes.

about:
  homepage: https://github.com/AdhocMan/spla
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Specialized Linear Algebra (SpLA) library, tailored for computational material science codes.
  description: |
    SPLA provides specialized functions for distributed matrix multiplication,
    as required in some computational material science codes. It aims for
    maximum computation and communication overlap when possible and allows any
    combination of host and device pointers if compiled with GPU support. C++, C
    and Fortran interfaces are available.
  repository: https://github.com/eth-cscs/spla
  documentation: https://spla.readthedocs.io/en/latest/?badge=latest

extra:
  recipe-maintainers:
    - AdhocMan
    - mkrack
